### ISSUE TITLE
Non affichage du profil d'un contributeur

### ISSUE THREAD

**Issue by gemmafelton** [gemmafelton/PPE-group#3]
Bonjour, 

Nous rencontrons un problème avec l'affichage de l'un de nos camarades sur notre git hub. @Simounawind fait parti de notre groupe et a déjà fait des commits sur notre page. En revanche, sur notre page d'accueil, il n'est pas affiché dans la partie "Contributeurs". C'est que lorsqu'on regarde dans Settings - Collaborateurs, qu'on voit son profil. Nous avons déjà essayé de lui enlever en tant que contributeur et de lui rajouter mais il n'a y rien qui fonctionne. 

Savez-vous comment nous pouvons afficher son profil sur notre page d'accueil? 

Merci d'avance.

**Comment by YoannDupont** [comment]
Bonsoir,

Pouvez-vous essayer de refaire la configuration du compte git dans le dépôt en terminal ? Il faut utiliser les commandes suivantes :

```
git config user.name "<gitusername>"
git config user.email "<gitemail>"
```

Où `<gitusername>` est le nom utilisateur sur Github et `<gitemail>` est l'email lié au compte Github.

Cordialement.

**Comment by Simounawind** [comment]
> Bonsoir,
> 
> Pouvez-vous essayer de refaire la configuration du compte git dans le dépôt en terminal ? Il faut utiliser les commandes suivantes :
> 
> ```
> git config user.name "<gitusername>"
> git config user.email "<gitemail>"
> ```
> 
> Où `<gitusername>` est le nom utilisateur sur Github et `<gitemail>` est l'email lié au compte Github.
> 
> Cordialement.

Merci, problem solved !
